export default [
  {
    _id: "u1",
    firstName: "Alice",
    lastName: "Zhang",
    username: "alice",
    password: "alice123",
    email: "alice@example.com",
    role: "STUDENT",
  },
  {
    _id: "u2",
    firstName: "Bob",
    lastName: "Smith",
    username: "bob",
    password: "bob123",
    email: "bob@example.com",
    role: "TA",
  },
  {
    _id: "u3",
    firstName: "Carol",
    lastName: "Lee",
    username: "carol",
    password: "carol123",
    email: "carol@example.com",
    role: "STUDENT",
  },
  {
    _id: "u4",
    firstName: "John",
    lastName: "Professor",
    username: "faculty",
    password: "faculty123",
    email: "faculty@example.com",
    role: "FACULTY",
  },
];
